neofetch
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# source ~/anaconda3/etc/profile.d/conda.sh  # commented out by conda initialize


#PowerLine
zplug "b-ryan/powerline-shell"

function powerline_precmd() {
    PS1="$(powerline-shell --shell zsh $?)"
}

function install_powerline_precmd() {
  for s in ${precmd_functions[@]}; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

# zplugの設定
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# syntax
zplug "chrissicool/zsh-256color"
zplug "Tarrasch/zsh-colors"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "ascii-soup/zsh-url-highlighter"

#zplug "zsh-users/zsh-autosuggestions", defer:2

# 未インストール項目をインストールする
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# コマンドをリンクして、PATH に追加し、プラグインは読み込む
zplug load --verbose

# プロンプトの設定
PROMPT="%n@%~ "

#色
alias ls='ls -G'
alias ll='ls -lG'
alias la='ls -laG'

export PATH=~/.local/bin/:$PATH

# zplugの設定ここまで
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
#__conda_setup="$('/Users/br171440/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
#if [ $? -eq 0 ]; then
#    eval "$__conda_setup"
#else
#    if [ -f "/Users/br171440/opt/anaconda3/etc/profile.d/conda.sh" ]; then
#        . "/Users/br171440/opt/anaconda3/etc/profile.d/conda.sh"
#    else
#        export PATH="/Users/br171440/opt/anaconda3/bin:$PATH"
#    fi
#fi
#unset __conda_setup
# <<< conda initialize <<<

export PATH="/Applications/Julia-1.6.app/Contents/Resources/julia/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

#alias juplab='cd ~/jupyter && jupyter lab'
alias setproxy="/bin/sh /Users/br171440/simple_proxy.sh set"
alias unsetproxy="/bin/sh /Users/br171440/simple_proxy.sh unset"

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#neofetch
clear
